// ========== TRAINING SCHEMAS ==========
const TRAINING_SCHEMAS = [
  {
    id: 'full-body-3x',
    foto: 'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    name: 'Full Body',
    icon: '💪',
    level: 'Beginner',
    level_en: 'Beginner',
    doel: 'Kracht & conditie',
    doel_en: 'Strength & conditioning',
    duur: '45-60 min',
    freq: '3x per week',
    beschrijving: 'Ideaal voor beginners. Traint alle spiergroepen in één sessie.',
    beschrijving_en: 'Ideal for beginners. Trains all muscle groups in one session.',
    kleur: '#4a7c59',
    oefeningen: [
      { name:'Barbell Squat',     icon:'🏋️', sets:3, reps:'8-10',  rest:'90 sec', youtube:'https://www.youtube.com/watch?v=ultWZbUMPL8', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Bench Press',       icon:'💪',  sets:3, reps:'8-10',  rest:'90 sec', youtube:'https://www.youtube.com/watch?v=SCVCLChPQFY', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Dumbbell Row',      icon:'🎿',  sets:3, reps:'10-12', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=pYcpY20QaE8', photo:'https://images.pexels.com/photos/3289711/pexels-photo-3289711.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Overhead Press',    icon:'🙌',  sets:3, reps:'10',    rest:'90 sec', youtube:'https://www.youtube.com/watch?v=2yjwXTZQDDI', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Romanian Deadlift', icon:'🦵',  sets:3, reps:'10-12', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=JCXUYuzwNrM', photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Plank',             icon:'🎯',  sets:3, reps:'45 sec',rest:'45 sec', youtube:'https://www.youtube.com/watch?v=ASdvN_XEl_c', photo:'https://images.pexels.com/photos/3775593/pexels-photo-3775593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    ]
  },
  {
    id: 'upper-lower',
    foto: 'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    name: 'Upper / Lower Split',
    icon: '🔀',
    level: 'Gevorderd',
    level_en: 'Advanced',
    doel: 'Kracht & spiermassa',
    doel_en: 'Strength & muscle mass',
    duur: '60-75 min',
    freq: '4x per week',
    beschrijving: 'Bovenlichaam of onderlichaam per sessie. Meer volume per spiergroep.',
    beschrijving_en: 'Upper body or lower body per session. More volume per muscle group.',
    kleur: '#2c5282',
    oefeningen: [
      { name:'Bench Press',       icon:'💪',  sets:4, reps:'6-8',   rest:'2 min',  youtube:'https://www.youtube.com/watch?v=SCVCLChPQFY', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Barbell Row',       icon:'🏋️', sets:4, reps:'6-8',   rest:'2 min',  youtube:'https://www.youtube.com/watch?v=FWJR5Ve8bnQ', photo:'https://images.pexels.com/photos/3289711/pexels-photo-3289711.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Overhead Press',    icon:'🙌',  sets:3, reps:'8-10',  rest:'90 sec', youtube:'https://www.youtube.com/watch?v=2yjwXTZQDDI', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Pull-ups',          icon:'🤸',  sets:3, reps:'6-10',  rest:'90 sec', youtube:'https://www.youtube.com/watch?v=eGo4IYlbE5g', photo:'https://images.pexels.com/photos/416717/pexels-photo-416717.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Barbell Squat',     icon:'🏋️', sets:4, reps:'6-8',   rest:'2 min',  youtube:'https://www.youtube.com/watch?v=ultWZbUMPL8', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Deadlift',          icon:'🔑',  sets:3, reps:'5',     rest:'3 min',  youtube:'https://www.youtube.com/watch?v=op9kVnSso6Q', photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Romanian Deadlift', icon:'🦵',  sets:3, reps:'10-12', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=JCXUYuzwNrM', photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Lunges',            icon:'🚶',  sets:3, reps:'12/been',rest:'75 sec',youtube:'https://www.youtube.com/watch?v=QOVaHwm-Q6U', photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    ]
  },
  {
    id: 'push-pull-legs',
    foto: 'https://images.pexels.com/photos/416717/pexels-photo-416717.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    name: 'Push / Pull / Legs',
    icon: '🔄',
    level: 'Gevorderd',
    level_en: 'Advanced',
    doel: 'Spiermassa',
    doel_en: 'Muscle mass',
    duur: '60-75 min',
    freq: '6x per week',
    beschrijving: 'Klassiek bodybuilding schema. Push (borst/schouders), Pull (rug/biceps), Legs apart.',
    beschrijving_en: 'Classic bodybuilding split. Push (chest/shoulders), Pull (back/biceps), Legs separately.',
    kleur: '#744210',
    oefeningen: [
      { name:'Bench Press',       icon:'💪',  sets:4, reps:'8-12',  rest:'90 sec', youtube:'https://www.youtube.com/watch?v=SCVCLChPQFY', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Incline Bench Press',icon:'📐', sets:3, reps:'10-12', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=DbFgADa2PL8', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Overhead Press',    icon:'🙌',  sets:3, reps:'10-12', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=2yjwXTZQDDI', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Lateral Raises',    icon:'↔️',  sets:3, reps:'15',    rest:'60 sec', youtube:'https://www.youtube.com/watch?v=3VcKaXpzqRo', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Pull-ups',          icon:'🤸',  sets:4, reps:'6-10',  rest:'90 sec', youtube:'https://www.youtube.com/watch?v=eGo4IYlbE5g', photo:'https://images.pexels.com/photos/416717/pexels-photo-416717.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Barbell Row',       icon:'🏋️', sets:4, reps:'8-10',  rest:'90 sec', youtube:'https://www.youtube.com/watch?v=FWJR5Ve8bnQ', photo:'https://images.pexels.com/photos/3289711/pexels-photo-3289711.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Barbell Squat',     icon:'🏋️', sets:4, reps:'8-10',  rest:'90 sec', youtube:'https://www.youtube.com/watch?v=ultWZbUMPL8', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Romanian Deadlift', icon:'🦵',  sets:3, reps:'10-12', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=JCXUYuzwNrM', photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Leg Press',         icon:'🦵',  sets:3, reps:'12-15', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=IZxyjW7MPJQ', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    ]
  },
  {
    id: 'herstel-mobiliteit',
    foto: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    name: 'Herstel & Mobiliteit',
    name_en: 'Recovery & Mobility',
    icon: '🌊',
    level: 'Alle niveaus',
    level_en: 'All levels',
    doel: 'Herstel & flexibiliteit',
    doel_en: 'Recovery & flexibility',
    duur: '30-45 min',
    freq: '1-2x per week',
    beschrijving: 'Actief hersteldag. Gericht op mobiliteit, stretching en verbetering van bewegingsbereik.',
    beschrijving_en: 'Active recovery day. Focused on mobility, stretching and improving range of motion.',
    kleur: '#4a7c59',
    oefeningen: [
      { name:'Wandelen',          name_en:'Walking', icon:'🚶',  sets:'', reps:'', rest:'', stappen:'8000-10000 stappen per dag', stappen_en:'8000-10000 steps per day', youtube:'https://www.youtube.com/watch?v=_kGESn8ArrU', photo:'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Foam rollen',       name_en:'Foam rolling', icon:'🌀',  sets:1, reps:'10 min', rest:'—',     youtube:'https://www.youtube.com/watch?v=eTCo_3sAE2s', photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Heup openers',      name_en:'Hip openers', icon:'🧘',  sets:3, reps:'60 sec', rest:'30 sec',youtube:'https://www.youtube.com/watch?v=42sCXjMTsKM', photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Nek & schouder stretch',name_en:'Neck & shoulder stretch',icon:'🤸',sets:3,reps:'30 sec',rest:'15 sec',youtube:'https://www.youtube.com/watch?v=4pKly2JojMw', photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Dead Bug',          icon:'🐛',  sets:3, reps:'8/kant', rest:'45 sec',youtube:'https://www.youtube.com/watch?v=SdDPV3zZRUU', photo:'https://images.pexels.com/photos/3775593/pexels-photo-3775593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Plank',             icon:'🎯',  sets:3, reps:'30 sec', rest:'30 sec',youtube:'https://www.youtube.com/watch?v=ASdvN_XEl_c', photo:'https://images.pexels.com/photos/3775593/pexels-photo-3775593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    ]
  },
  {
    id: 'kracht-5x5',
    foto: 'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    name: 'Kracht 5×5',
    name_en: 'Strength 5×5',
    icon: '🔑',
    level: 'Intermediair',
    level_en: 'Intermediate',
    doel: 'Maximale kracht',
    doel_en: 'Maximum strength',
    duur: '60-70 min',
    freq: '3x per week',
    beschrijving: 'Gebaseerd op StrongLifts 5×5. Focus op de grote basisoefeningen voor maximale krachtontwikkeling.',
    beschrijving_en: 'Based on StrongLifts 5×5. Focus on the big compound lifts for maximum strength development.',
    kleur: '#97266d',
    oefeningen: [
      { name:'Barbell Squat',   icon:'🏋️', sets:5, reps:'5', rest:'3 min', youtube:'https://www.youtube.com/watch?v=ultWZbUMPL8', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Bench Press',     icon:'💪',  sets:5, reps:'5', rest:'3 min', youtube:'https://www.youtube.com/watch?v=SCVCLChPQFY', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Barbell Row',     icon:'🏋️', sets:5, reps:'5', rest:'3 min', youtube:'https://www.youtube.com/watch?v=FWJR5Ve8bnQ', photo:'https://images.pexels.com/photos/3289711/pexels-photo-3289711.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Overhead Press',  icon:'🙌',  sets:5, reps:'5', rest:'3 min', youtube:'https://www.youtube.com/watch?v=2yjwXTZQDDI', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Deadlift',        icon:'🔑',  sets:1, reps:'5', rest:'3 min', youtube:'https://www.youtube.com/watch?v=op9kVnSso6Q', photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    ]
  },
  {
    id: 'cardio-conditie',
    foto: 'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    name: 'Cardio & Conditie',
    name_en: 'Cardio & Conditioning',
    icon: '🏃',
    level: 'Alle niveaus',
    level_en: 'All levels',
    doel: 'Conditie & vetverbranding',
    doel_en: 'Conditioning & fat burning',
    duur: '40-50 min',
    freq: '3-5x per week',
    beschrijving: 'Combinatie van cardio en functionele oefeningen voor betere conditie en vetverbranding.',
    beschrijving_en: 'Combination of cardio and functional exercises for better conditioning and fat burning.',
    kleur: '#c05621',
    oefeningen: [
      { name:'Lopen',           name_en:'Running', icon:'🏃',  sets:1, reps:'20 min', rest:'—',     youtube:'https://www.youtube.com/watch?v=_kGESn8ArrU', photo:'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Burpees',         icon:'💥',  sets:3, reps:'10',     rest:'60 sec',youtube:'https://www.youtube.com/watch?v=TU8QYVW0gDU', photo:'https://images.pexels.com/photos/3837757/pexels-photo-3837757.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Push-ups',        icon:'🤸',  sets:3, reps:'15',     rest:'45 sec',youtube:'https://www.youtube.com/watch?v=IODxDxX7oi4', photo:'https://images.pexels.com/photos/3837757/pexels-photo-3837757.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Plank',           icon:'🎯',  sets:3, reps:'45 sec', rest:'30 sec',youtube:'https://www.youtube.com/watch?v=ASdvN_XEl_c', photo:'https://images.pexels.com/photos/3775593/pexels-photo-3775593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Farmer Carry',    icon:'🧳',  sets:3, reps:'40m',    rest:'90 sec',youtube:'https://www.youtube.com/watch?v=rt17lmnaLSM', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      { name:'Ab Wheel',        icon:'⚙️',  sets:3, reps:'8-10',   rest:'60 sec',youtube:'https://www.youtube.com/watch?v=vGFQeQ8YkQ4', photo:'https://images.pexels.com/photos/3775593/pexels-photo-3775593.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    ]
  },
];


// ========== EXTRA OEFENINGEN ==========
const EXTRA_EXERCISES = [
  { group:'Borst', group_en:'Chest', icon:'💪', color:'#744210', exercises:[
    { id:'ex-bp',   name:'Bench Press',         icon:'💪', sets:3, reps:'8-10', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=SCVCLChPQFY', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-dbp',  name:'Dumbbell Press',       icon:'💪', sets:3, reps:'10-12', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=VmB1G1K7v94', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-pu',   name:'Push-ups',             icon:'🤸', sets:3, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=IODxDxX7oi4', photo:'https://images.pexels.com/photos/4775232/pexels-photo-4775232.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-ibp',  name:'Incline Bench Press',  icon:'📐', sets:3, reps:'10', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=DbFgADa2PL8', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-cf',   name:'Cable Fly',            icon:'🔗', sets:3, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=Iwe6AmxVf7o', photo:'https://images.pexels.com/photos/5327505/pexels-photo-5327505.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-dbfly',name:'Dumbbell Fly',         icon:'🦋', sets:3, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=eozdVDA78K0', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
  ]},
  { group:'Rug', group_en:'Back', icon:'🎿', color:'#553c9a', exercises:[
    { id:'ex-dr',   name:'Dumbbell Row',         icon:'🎿', sets:3, reps:'10-12', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=pYcpY20QaE8', photo:'https://images.pexels.com/photos/3289711/pexels-photo-3289711.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-br',   name:'Barbell Row',          icon:'🏋️', sets:3, reps:'8-10', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=FWJR5Ve8bnQ', photo:'https://images.pexels.com/photos/3289711/pexels-photo-3289711.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-pul',  name:'Pull-ups',             icon:'🤸', sets:3, reps:'6-10', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=eGo4IYlbE5g', photo:'https://images.pexels.com/photos/9644816/pexels-photo-9644816.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-chu',  name:'Chin-up',              icon:'🤸', sets:3, reps:'6-10', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=brhRXlOhsAM', photo:'https://images.pexels.com/photos/9644816/pexels-photo-9644816.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-ld',   name:'Lat Pulldown',         icon:'⬇️', sets:3, reps:'10-12', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=CAwf7n6Luuc', photo:'https://images.pexels.com/photos/5327505/pexels-photo-5327505.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-scr',  name:'Seated Cable Row',     icon:'🔗', sets:3, reps:'10-12', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=GZbfZ033f74', photo:'https://images.pexels.com/photos/5327505/pexels-photo-5327505.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-bext', name:'Back Extension',       icon:'🏋️', sets:3, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=ph3pddpKzzw', photo:'https://images.pexels.com/photos/3289711/pexels-photo-3289711.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
  ]},
  { group:'Schouders', group_en:'Shoulders', icon:'🙌', color:'#97266d', exercises:[
    { id:'ex-ohp',  name:'Overhead Press',       icon:'🙌', sets:3, reps:'8-10', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=2yjwXTZQDDI', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-dsp',  name:'Dumbbell Shoulder Press', icon:'💪', sets:3, reps:'10-12', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=B-aVuyhvLHU', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-sbp',  name:'Shoulder Bench Press',icon:'🏋️', sets:4, reps:'8-10', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=Wqnal9E2RYI', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-lr',   name:'Lateral Raises',       icon:'↔️', sets:3, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=3VcKaXpzqRo', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-fp',   name:'Face Pull',            icon:'🎯', sets:3, reps:'15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=rep-qVOkqgk', photo:'https://images.pexels.com/photos/5327505/pexels-photo-5327505.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-rf',   name:'Reverse Fly',          icon:'🦋', sets:3, reps:'15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=Pq-mQ76-VWg', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
  ]},
  { group:'Benen', group_en:'Legs', icon:'🦵', color:'#2c5282', exercises:[
    { id:'ex-sqbw', name:'Squats',               icon:'🦵', sets:3, reps:'15-20', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=aclHkVaku9U', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-sq',   name:'Barbell Squat',        icon:'🏋️', sets:4, reps:'8-10', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=ultWZbUMPL8', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-dbsq', name:'Dumbbell Squat',       icon:'🏋️', sets:3, reps:'12-15', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=U4pFSHFdDQc', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-gs',   name:'Goblet Squat',         icon:'🏋️', sets:3, reps:'10-12', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=MxsFDhcyFyE', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-lp',   name:'Leg Press',            icon:'🦵', sets:3, reps:'10-12', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=IZxyjW7MPJQ', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-lun',  name:'Lunges',               icon:'🚶', sets:3, reps:'12/been', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=QOVaHwm-Q6U', photo:'https://images.pexels.com/photos/8770407/pexels-photo-8770407.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-dblun',name:'Dumbbell Lunges',      icon:'🚶', sets:3, reps:'12/been', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=D7KaRcUTQeE', photo:'https://images.pexels.com/photos/8770407/pexels-photo-8770407.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-rdl',  name:'Romanian Deadlift',    icon:'🦵', sets:3, reps:'10-12', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=JCXUYuzwNrM', photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-lc',   name:'Leg Curl (machine)',   icon:'🦵', sets:3, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=1Tq3QdYUuHs', photo:'https://images.pexels.com/photos/13965338/pexels-photo-13965338.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
  ]},
  { group:'Core', group_en:'Core', icon:'🎯', color:'#c05621', exercises:[
    { id:'ex-pl',   name:'Plank',                icon:'🎯', sets:3, reps:'45 sec', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=ASdvN_XEl_c', photo:'https://images.pexels.com/photos/4047103/pexels-photo-4047103.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-spl',  name:'Side Plank',           icon:'↕️', sets:3, reps:'30 sec', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=K2iEFHkuCHM', photo:'https://images.pexels.com/photos/4047103/pexels-photo-4047103.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-cr',   name:'Crunches',             icon:'🔄', sets:3, reps:'20', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=Xyd_fa5zoEU', photo:'https://images.pexels.com/photos/4047103/pexels-photo-4047103.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-aw',   name:'Ab Wheel',             icon:'⚙️', sets:3, reps:'8-10', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=vGFQeQ8YkQ4', photo:'https://images.pexels.com/photos/4047103/pexels-photo-4047103.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-db',   name:'Dead Bug',             icon:'🐛', sets:3, reps:'8/kant', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=SdDPV3zZRUU', photo:'https://images.pexels.com/photos/4047103/pexels-photo-4047103.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-abs',  name:'Serie abs exercises',  name_en:'Abs circuit', icon:'🔥', sets:3, reps:'circuit', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=Xyd_fa5zoEU', photo:'https://images.pexels.com/photos/4047103/pexels-photo-4047103.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-lr2',  name:'Leg Raises',           icon:'🦵', sets:3, reps:'15', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=l4kQd9eWclE', photo:'https://images.pexels.com/photos/4047103/pexels-photo-4047103.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-bc2',  name:'Bicycle Crunches',     icon:'🚴', sets:3, reps:'20', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=9FGilxCbdz8', photo:'https://images.pexels.com/photos/4047103/pexels-photo-4047103.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-rt',   name:'Russian Twist',        icon:'🔄', sets:3, reps:'20', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=wkD8rjkodUI', photo:'https://images.pexels.com/photos/4047103/pexels-photo-4047103.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-mc',   name:'Mountain Climbers',    icon:'🧗', sets:3, reps:'30 sec', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=nmwgirgXLYM', photo:'https://images.pexels.com/photos/4047103/pexels-photo-4047103.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-hkr',  name:'Hanging Knee Raises',  icon:'🤸', sets:3, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=Pr1ieGZ5atk', photo:'https://images.pexels.com/photos/9644816/pexels-photo-9644816.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-fk',   name:'Flutter Kicks',        icon:'🦵', sets:3, reps:'30 sec', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=ANVdMDaYRts', photo:'https://images.pexels.com/photos/4047103/pexels-photo-4047103.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-vup',  name:'V-ups',                icon:'✌️', sets:3, reps:'15', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=iP2fjvG0g3w', photo:'https://images.pexels.com/photos/4047103/pexels-photo-4047103.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
  ]},
  { group:'Full body', group_en:'Full body', icon:'🔑', color:'#276749', exercises:[
    { id:'ex-dl',   name:'Deadlift',             icon:'🔑', sets:4, reps:'4-6', rest:'3 min', youtube:'https://www.youtube.com/watch?v=op9kVnSso6Q', photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-fc',   name:'Farmer Carry',         icon:'🧳', sets:3, reps:'40m', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=rt17lmnaLSM', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-ke',   name:'Kettlebell Swing',     icon:'🫙', sets:3, reps:'15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=YSxHifyI6s8', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-bc',   name:'Burpees',              icon:'💥', sets:3, reps:'10', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=TU8QYVW0gDU', photo:'https://images.pexels.com/photos/4775232/pexels-photo-4775232.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-grip', name:'Handtrainer',          name_en:'Grip trainer', icon:'✊', sets:3, reps:'20/hand', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=o4wQ0XiGOkg', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
  ]},
  { group:'Biceps', group_en:'Biceps', icon:'💪', color:'#b7791f', exercises:[
    { id:'ex-bbc',  name:'Barbell Curl',          icon:'💪', sets:3, reps:'10-12', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=kwG2ipFRgfo', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-dbc',  name:'Dumbbell Curl',          icon:'💪', sets:3, reps:'10-12', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=ykJmrZ5v0Oo', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-hac',  name:'Hammer Curl',            icon:'🔨', sets:3, reps:'10-12', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=zC3nLlEvin4', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-prc',  name:'Preacher Curl',          icon:'💪', sets:3, reps:'10-12', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=fIWP-FRFNU0', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-cac',  name:'Cable Curl',             icon:'🔗', sets:3, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=NFzTWp2qpiE', photo:'https://images.pexels.com/photos/5327505/pexels-photo-5327505.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-conc', name:'Concentration Curl',     icon:'💪', sets:3, reps:'12/arm', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=0AUGkch3tzc', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
  ]},
  { group:'Triceps', group_en:'Triceps', icon:'💥', color:'#9b2c2c', exercises:[
    { id:'ex-tpd',  name:'Tricep Pushdown',        icon:'⬇️', sets:3, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=2-LAMcpzODU', photo:'https://images.pexels.com/photos/5327505/pexels-photo-5327505.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-skc',  name:'Skull Crushers',         icon:'💀', sets:3, reps:'10-12', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=d_KZxkY_0cM', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-dip1', name:'Dips 1 (bank)',           icon:'🤸', sets:3, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=0326dy_-CzM', photo:'https://images.pexels.com/photos/9644816/pexels-photo-9644816.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-dip2', name:'Dips 2 (parallel bars)', icon:'🤸', sets:3, reps:'8-12', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=wjUmnZH528Y', photo:'https://images.pexels.com/photos/9644816/pexels-photo-9644816.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-ote',  name:'Overhead Tricep Extension', icon:'🙌', sets:3, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=YbX7Wd8jQ-Q', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-cgbp', name:'Close Grip Bench Press', icon:'🏋️', sets:3, reps:'8-10', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=nEF0bv2FW94', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-kbk',  name:'Kickbacks',              icon:'💪', sets:3, reps:'12-15', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=6SS6K3lAwZ8', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
  ]},
  { group:'Trapezius', group_en:'Trapezius', icon:'🦍', color:'#4a5568', exercises:[
    { id:'ex-dbs',  name:'Dumbbell Shrugs',        icon:'🤷', sets:3, reps:'15-20', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=g6qbq4Lf1FI', photo:'https://images.pexels.com/photos/3289711/pexels-photo-3289711.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-bbs',  name:'Barbell Shrugs',         icon:'🤷', sets:4, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=cJRVVxmytaM', photo:'https://images.pexels.com/photos/3289711/pexels-photo-3289711.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-uro',  name:'Upright Row',            icon:'⬆️', sets:3, reps:'10-12', rest:'75 sec', youtube:'https://www.youtube.com/watch?v=UBMIAhCpFDk', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-casr', name:'Cable Shrug',            icon:'🔗', sets:3, reps:'15-20', rest:'45 sec', youtube:'https://www.youtube.com/watch?v=e3LTd0gJpGQ', photo:'https://images.pexels.com/photos/5327505/pexels-photo-5327505.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-curo', name:'Cable Upright Row',       icon:'🔗', sets:3, reps:'12-15', rest:'60 sec', youtube:'https://www.youtube.com/watch?v=UBMIAhCpFDk', photo:'https://images.pexels.com/photos/5327505/pexels-photo-5327505.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-fpr',  name:'Farm Walk (trap focus)',  icon:'🧳', sets:3, reps:'30m', rest:'90 sec', youtube:'https://www.youtube.com/watch?v=rt17lmnaLSM', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
  ]},
  { group:'Cardio', group_en:'Cardio', icon:'🏃', color:'#4a7c59', exercises:[
    { id:'ex-wa',   name:'Wandelen',             name_en:'Walking', icon:'\u{1F6B6}', sets:'', reps:'', rest:'', stappen:'8000-10000 stappen per dag', stappen_en:'8000-10000 steps per day', youtube:'https://www.youtube.com/watch?v=_kGESn8ArrU', photo:'https://images.pexels.com/photos/1556710/pexels-photo-1556710.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-fi',   name:'Fietsen',             name_en:'Cycling', icon:'🚴', sets:1, reps:'30 min', rest:'—', youtube:'https://www.youtube.com/watch?v=_kGESn8ArrU', photo:'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
    { id:'ex-ri',   name:'Roeien (machine)',     name_en:'Rowing (machine)', icon:'🚣', sets:1, reps:'20 min', rest:'—', youtube:'https://www.youtube.com/watch?v=_kGESn8ArrU', photo:'https://images.pexels.com/photos/4162481/pexels-photo-4162481.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
  ]},
];


// ========== OEFENINGEN PER TYPE ==========
const EXERCISES = {
  herstel: [
    { name:'Wandelen', name_en:'Walking', icon:'🚶', sets:1, reps:'30 min', rest:'—',
      tip:'Rustig tempo, frisse lucht. Geen prestatie-druk — dit is actief herstel.',
      tip_en:'Easy pace, fresh air. No pressure to perform — this is active recovery.',
      youtube:'https://www.youtube.com/watch?v=aXItOY0sLRY',
      photo:'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Fietsen (rustig)', name_en:'Cycling (easy)', icon:'🚴', sets:1, reps:'30 min', rest:'—', tip:'Laag tempo, geen inspanning. Bloed in beweging houden.', tip_en:'Low pace, no effort. Keep the blood flowing.', youtube:'https://www.youtube.com/watch?v=aXItOY0sLRY', photo:'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Zwemmen (rustig)', name_en:'Swimming (easy)', icon:'🏊', sets:1, reps:'20 min', rest:'—', tip:'Kalm baantjes trekken. Gewrichtsvriendelijk herstel.', tip_en:'Calm laps. Joint-friendly recovery.', youtube:'https://www.youtube.com/watch?v=aXItOY0sLRY', photo:'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Foam rollen', name_en:'Foam rolling', icon:'🌀', sets:1, reps:'10-15 min', rest:'—',
      tip:'Rol langzaam over gespannen spiergroepen. Houd 30 sec op pijnlijke punten.',
      tip_en:'Roll slowly over tight muscle groups. Hold 30 sec on tender spots.',
      youtube:'https://www.youtube.com/watch?v=eTCo_3sAE2s',
      photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Massage bal', name_en:'Massage ball', icon:'⚽', sets:1, reps:'10 min', rest:'—', tip:'Gebruik een tennisbal of lacrosse bal op voeten en billen.', tip_en:'Use a tennis or lacrosse ball on feet and glutes.', youtube:'https://www.youtube.com/watch?v=eTCo_3sAE2s', photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Nek & schouder stretch', name_en:'Neck & shoulder stretch', icon:'🤸', sets:3, reps:'30 sec', rest:'15 sec',
      tip:'Kantel je hoofd naar rechts, houd 30 sec. Herhaal links. Ontspannen ademhalen.',
      tip_en:'Tilt your head to the right, hold 30 sec. Repeat left. Breathe relaxed.',
      youtube:'https://www.youtube.com/watch?v=4pKly2JojMw',
      photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Wervelkolom rotatie', name_en:'Spinal rotation', icon:'🔄', sets:3, reps:'10 herh', rest:'20 sec', tip:'Zit rechtop, draai langzaam van links naar rechts. Rug recht.', tip_en:'Sit upright, rotate slowly from left to right. Keep your back straight.', youtube:'https://www.youtube.com/watch?v=4pKly2JojMw', photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Borstkas openen', name_en:'Chest opener', icon:'🫁', sets:3, reps:'30 sec', rest:'15 sec', tip:'Handen achter je hoofd, ellebogen naar achteren. Voel de stretch in je borst.', tip_en:'Hands behind your head, elbows back. Feel the stretch in your chest.', youtube:'https://www.youtube.com/watch?v=4pKly2JojMw', photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Heup openers', name_en:'Hip openers', icon:'🧘', sets:3, reps:'60 sec', rest:'30 sec',
      tip:'Zit in een diepe squat, houd vast aan iets. Laat je heupen los.',
      tip_en:'Sit in a deep squat, hold onto something. Let your hips loosen.',
      youtube:'https://www.youtube.com/watch?v=YQmpO6OpBoY',
      photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Duif pose (yoga)', name_en:'Pigeon pose (yoga)', icon:'🕊️', sets:2, reps:'60 sec per kant', rest:'30 sec', tip:'Leg je onderbeen voor je neer, strek het andere been naar achteren. Diepe heupstretch.', tip_en:'Place your shin in front of you, stretch the other leg back. Deep hip stretch.', youtube:'https://www.youtube.com/watch?v=YQmpO6OpBoY', photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Hip flexor stretch', icon:'🦵', sets:3, reps:'45 sec per kant', rest:'20 sec', tip:'Knie op de grond, andere voet voor. Duw heupen naar voren.', tip_en:'Knee on the ground, other foot forward. Push hips forward.', youtube:'https://www.youtube.com/watch?v=YQmpO6OpBoY', photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Lichte core activatie', name_en:'Light core activation', icon:'🎯', sets:3, reps:'10 herh', rest:'45 sec',
      tip:'Plank op knieën of dead bugs. Geen kracht — alleen activatie.',
      tip_en:'Plank on knees or dead bugs. No strength focus — just activation.',
      youtube:'https://www.youtube.com/watch?v=4XLEnwUr1d8',
      photo:'https://images.pexels.com/photos/4164453/pexels-photo-4164453.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Dead bug', icon:'🐛', sets:3, reps:'8 per kant', rest:'45 sec', tip:'Lig op rug, armen omhoog. Strek tegengestelde arm en been, core strak.', tip_en:'Lie on your back, arms up. Extend opposite arm and leg, core tight.', youtube:'https://www.youtube.com/watch?v=SdDPV3zZRUU', photo:'https://images.pexels.com/photos/4164453/pexels-photo-4164453.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Bird dog', icon:'🐦', sets:3, reps:'8 per kant', rest:'45 sec', tip:'Op handen en knieën. Strek tegengestelde arm en been. Heupen stabiel houden.', tip_en:'On hands and knees. Extend opposite arm and leg. Keep hips stable.', youtube:'https://www.youtube.com/watch?v=wiFNA3sqjCA', photo:'https://images.pexels.com/photos/4164453/pexels-photo-4164453.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
  ],
  normaal: [
    { name:'Barbell Squat', icon:'🏋️', sets:4, reps:'8-10', rest:'90 sec',
      tip:'Voeten op schouderbreedte. Knieën volgen je tenen. Rug recht houden door de hele beweging.',
      tip_en:'Feet shoulder-width apart. Knees track your toes. Keep your back straight throughout.',
      youtube:'https://www.youtube.com/watch?v=ultWZbUMPL8',
      photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Goblet Squat', icon:'🏋️', sets:4, reps:'10-12', rest:'90 sec', tip:'Houd één dumbbell voor je borst. Makkelijker voor de rug, zelfde spiergroepen.', tip_en:'Hold one dumbbell in front of your chest. Easier on the back, same muscle groups.', youtube:'https://www.youtube.com/watch?v=MxsFDhcyFyE', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Leg Press', icon:'🦵', sets:4, reps:'10-12', rest:'90 sec', tip:'Machine-alternatief. Voeten iets breder dan schouderbreedte. Knieën niet naar binnen.', tip_en:'Machine alternative. Feet slightly wider than shoulder-width. Knees do not cave in.', youtube:'https://www.youtube.com/watch?v=IZxyjW7MPJQ', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Lunges', icon:'🚶', sets:3, reps:'12 per been', rest:'75 sec', tip:'Stap naar voren, knie boven enkel. Romp rechtop houden.', tip_en:'Step forward, knee above ankle. Keep torso upright.', youtube:'https://www.youtube.com/watch?v=QOVaHwm-Q6U', photo:'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Bench Press', icon:'💪', sets:4, reps:'8-10', rest:'90 sec',
      tip:'Schouderbladen samenknijpen en in de bank drukken. Stang raakt je borst licht.',
      tip_en:'Squeeze shoulder blades together and press into the bench. Bar lightly touches your chest.',
      youtube:'https://www.youtube.com/watch?v=SCVCLChPQFY',
      photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Dumbbell Press', icon:'💪', sets:4, reps:'10-12', rest:'90 sec', tip:'Dumbbells geven meer bewegingsvrijheid. Ellebogen iets gebogen bij het laten zakken.', tip_en:'Dumbbells give more freedom of movement. Elbows slightly bent when lowering.', youtube:'https://www.youtube.com/watch?v=SCVCLChPQFY', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Push-ups', icon:'🤸', sets:4, reps:'12-15', rest:'75 sec', tip:'Geen materiaal nodig. Handen iets breder dan schouderbreedte. Borst raakt de grond.', tip_en:'No equipment needed. Hands slightly wider than shoulder-width. Chest touches the ground.', youtube:'https://www.youtube.com/watch?v=IODxDxX7oi4', photo:'https://images.pexels.com/photos/3837757/pexels-photo-3837757.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Cable Fly', icon:'🔗', sets:3, reps:'12-15', rest:'75 sec', tip:'Isolatieoefening borst. Armen licht gebogen, breng handen samen voor je borst.', tip_en:'Chest isolation exercise. Arms slightly bent, bring hands together in front of your chest.', youtube:'https://www.youtube.com/watch?v=Iwe6AmxVf7o', photo:'https://images.pexels.com/photos/4162481/pexels-photo-4162481.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Dumbbell Row', icon:'🎿', sets:3, reps:'10-12', rest:'75 sec',
      tip:'Trek de elleboog omhoog, niet de hand. Voel de contractie in je rug.',
      tip_en:'Pull the elbow up, not the hand. Feel the contraction in your back.',
      youtube:'https://www.youtube.com/watch?v=pYcpY20QaE8',
      photo:'https://images.pexels.com/photos/3837757/pexels-photo-3837757.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Barbell Row', icon:'🏋️', sets:3, reps:'8-10', rest:'90 sec', tip:'Romp voorover, stang naar navel trekken. Rug recht houden.', tip_en:'Bend forward, pull the bar to your navel. Keep your back straight.', youtube:'https://www.youtube.com/watch?v=pYcpY20QaE8', photo:'https://images.pexels.com/photos/3837757/pexels-photo-3837757.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Seated Cable Row', icon:'🔗', sets:3, reps:'10-12', rest:'75 sec', tip:'Trek naar je navel. Schouderbladen samenknijpen aan het einde van de beweging.', tip_en:'Pull to your navel. Squeeze shoulder blades together at the end of the movement.', youtube:'https://www.youtube.com/watch?v=GZbfZ033f74', photo:'https://images.pexels.com/photos/4162481/pexels-photo-4162481.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Pull-ups', icon:'🤸', sets:3, reps:'6-10', rest:'90 sec', tip:'Volle bewegingsuitslag. Start hangend, eindig met kin boven de bar.', tip_en:'Full range of motion. Start hanging, finish with chin above the bar.', youtube:'https://www.youtube.com/watch?v=eGo4IYlbE5g', photo:'https://images.pexels.com/photos/416717/pexels-photo-416717.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Overhead Press', icon:'🙌', sets:3, reps:'8-10', rest:'90 sec',
      tip:'Buik aanspannen, pers recht omhoog. Hoofd iets naar achteren als de stang passeert.',
      tip_en:'Brace your core, press straight up. Head slightly back as the bar passes.',
      youtube:'https://www.youtube.com/watch?v=2yjwXTZQDDI',
      photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Dumbbell Shoulder Press', icon:'💪', sets:3, reps:'10-12', rest:'90 sec', tip:'Zittend of staand. Dumbbells naast je hoofd, pers omhoog zonder te wiegen.', tip_en:'Seated or standing. Dumbbells next to your head, press up without swaying.', youtube:'https://www.youtube.com/watch?v=B-aVuyhvLHU', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Lateral Raises', icon:'↔️', sets:3, reps:'12-15', rest:'60 sec', tip:'Lichte dumbbells. Armen zijwaarts heffen tot schouderhoogte. Langzaam zakken.', tip_en:'Light dumbbells. Raise arms sideways to shoulder height. Lower slowly.', youtube:'https://www.youtube.com/watch?v=3VcKaXpzqRo', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Plank', icon:'🎯', sets:3, reps:'45 sec', rest:'45 sec',
      tip:'Romp recht als een plank. Billen niet omhoog, rug niet hol. Adem rustig.',
      tip_en:'Torso straight like a plank. Hips not up, back not arched. Breathe calmly.',
      youtube:'https://www.youtube.com/watch?v=ASdvN_XEl_c',
      photo:'https://images.pexels.com/photos/4164453/pexels-photo-4164453.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Side Plank', icon:'↕️', sets:3, reps:'30 sec per kant', rest:'45 sec', tip:'Op één elleboog en voet. Heupen omhoog, lichaam rechte lijn.', tip_en:'On one elbow and foot. Hips up, body in a straight line.', youtube:'https://www.youtube.com/watch?v=ASdvN_XEl_c', photo:'https://images.pexels.com/photos/4164453/pexels-photo-4164453.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Ab Wheel', icon:'⚙️', sets:3, reps:'8-10', rest:'60 sec', tip:'Begin op knieën. Rol langzaam naar voren, core strak. Rol terug met buikspieren.', tip_en:'Start on your knees. Roll forward slowly, core tight. Roll back using your abs.', youtube:'https://www.youtube.com/watch?v=vGFQeQ8YkQ4', photo:'https://images.pexels.com/photos/4164453/pexels-photo-4164453.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Crunches', icon:'🔄', sets:3, reps:'20', rest:'45 sec', tip:'Handen achter hoofd, ellebogen breed. Til schouders op, niet je nek.', tip_en:'Hands behind head, elbows wide. Lift your shoulders, not your neck.', youtube:'https://www.youtube.com/watch?v=Xyd_fa5zoEU', photo:'https://images.pexels.com/photos/4164453/pexels-photo-4164453.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Romanian Deadlift', icon:'🦵', sets:3, reps:'10-12', rest:'90 sec',
      tip:'Houd de stang dicht bij je benen, knik vanuit de heupen. Voel de rek in je hamstrings.',
      tip_en:'Keep the bar close to your legs, hinge from the hips. Feel the stretch in your hamstrings.',
      youtube:'https://www.youtube.com/watch?v=JCXUYuzwNrM',
      photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Dumbbell RDL', icon:'🏋️', sets:3, reps:'12', rest:'90 sec', tip:'Zelfde beweging met dumbbells. Makkelijker te controleren dan stang.', tip_en:'Same movement with dumbbells. Easier to control than a bar.', youtube:'https://www.youtube.com/watch?v=hCDzSR6bW10', photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Good Morning', icon:'🌅', sets:3, reps:'10-12', rest:'90 sec', tip:'Stang op schouders, buig voorover vanuit heupen. Rug recht, knieën licht gebogen.', tip_en:'Bar on shoulders, bend forward from the hips. Back straight, knees slightly bent.', youtube:'https://www.youtube.com/watch?v=YA-h3n9L4YU', photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Leg Curl (machine)', icon:'🦵', sets:3, reps:'12-15', rest:'75 sec', tip:'Isolatieoefening voor hamstrings. Gecontroleerd bewegen, geen gewicht laten vallen.', tip_en:'Isolation exercise for hamstrings. Controlled movement, do not let the weight drop.', youtube:'https://www.youtube.com/watch?v=1Tq3QdYUuHs', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
  ],
  zwaar: [
    { name:'Barbell Squat', icon:'🏋️', sets:5, reps:'5', rest:'3 min',
      tip:'Zwaar gewicht, volle diepte. Ademhalen in voor de beweging — Valsalva techniek.',
      tip_en:'Heavy weight, full depth. Breathe in before the movement — Valsalva technique.',
      youtube:'https://www.youtube.com/watch?v=ultWZbUMPL8',
      photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Front Squat', icon:'🏋️', sets:5, reps:'4-5', rest:'3 min', tip:'Stang voor op schouders. Rechtopere romp dan back squat. Technisch moeilijker.', tip_en:'Bar in front on shoulders. More upright torso than a back squat. Technically harder.', youtube:'https://www.youtube.com/watch?v=m4ytaCJZpl0', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Hack Squat', icon:'🦵', sets:4, reps:'6-8', rest:'2 min', tip:'Machine-squat. Minder belasting op rug, zelfde beenspieren.', tip_en:'Machine squat. Less load on the back, same leg muscles.', youtube:'https://www.youtube.com/watch?v=0tn5K9NlCfo', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Deadlift', icon:'🔑', sets:4, reps:'4-6', rest:'3 min',
      tip:'Bar boven je middelvoet. Trek de spanning eruit voor je optilt. Explosief omhoog, gecontroleerd terug.',
      tip_en:'Bar above your mid-foot. Pull the slack out before you lift. Explosive up, controlled back down.',
      youtube:'https://www.youtube.com/watch?v=op9kVnSso6Q',
      photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Sumo Deadlift', icon:'🏋️', sets:4, reps:'4-6', rest:'3 min', tip:'Voeten wijd, handen smal. Minder heupbeweging, meer benen. Goed voor korte torso.', tip_en:'Feet wide, hands narrow. Less hip movement, more legs. Good for a short torso.', youtube:'https://www.youtube.com/watch?v=jADPhCJFELs', photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Trap Bar Deadlift', icon:'🔷', sets:4, reps:'5-6', rest:'3 min', tip:'Rugvriendelijker alternatief. Gewicht naast je lichaam in plaats van voor je.', tip_en:'Back-friendlier alternative. Weight next to your body instead of in front of you.', youtube:'https://www.youtube.com/watch?v=B4l84LDKM4c', photo:'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Bench Press', icon:'💪', sets:4, reps:'6-8', rest:'2 min',
      tip:'Arching mag — schouderbladen vastzetten. Explosieve push, langzame laadfase (3 sec neer).',
      tip_en:'Arching is fine — lock your shoulder blades. Explosive push, slow lowering phase (3 sec down).',
      youtube:'https://www.youtube.com/watch?v=SCVCLChPQFY',
      photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Incline Bench Press', icon:'📐', sets:4, reps:'6-8', rest:'2 min', tip:'Bank schuin (30°). Meer nadruk op bovenkant borst en schouders.', tip_en:'Bench tilted (30°). More emphasis on upper chest and shoulders.', youtube:'https://www.youtube.com/watch?v=SCVCLChPQFY', photo:'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Weighted Push-ups', icon:'🤸', sets:4, reps:'8-12', rest:'90 sec', tip:'Gewichtsplaat op rug of gewichtsvest. Zelfde bewegingspatroon als bench press.', tip_en:'Weight plate on your back or a weight vest. Same movement pattern as bench press.', youtube:'https://www.youtube.com/watch?v=IODxDxX7oi4', photo:'https://images.pexels.com/photos/3837757/pexels-photo-3837757.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Pull-ups', icon:'🤸', sets:4, reps:'6-8', rest:'2 min',
      tip:'Volle bewegingsuitslag. Start met hangende armen, eindig met kin boven de bar.',
      tip_en:'Full range of motion. Start with hanging arms, finish with chin above the bar.',
      youtube:'https://www.youtube.com/watch?v=eGo4IYlbE5g',
      photo:'https://images.pexels.com/photos/416717/pexels-photo-416717.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Weighted Pull-ups', icon:'⚖️', sets:4, reps:'5-6', rest:'2 min', tip:'Gewichtsriem of dumbbell tussen je knieën. Zware variant voor gevorderden.', tip_en:'Weight belt or dumbbell between your knees. Heavy variant for advanced trainees.', youtube:'https://www.youtube.com/watch?v=eGo4IYlbE5g', photo:'https://images.pexels.com/photos/416717/pexels-photo-416717.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Lat Pulldown', icon:'⬇️', sets:4, reps:'8-10', rest:'90 sec', tip:'Machine-alternatief. Trek stang naar borst. Schouderbladen samenknijpen onderaan.', tip_en:'Machine alternative. Pull the bar to your chest. Squeeze shoulder blades at the bottom.', youtube:'https://www.youtube.com/watch?v=CAwf7n6Luuc', photo:'https://images.pexels.com/photos/4162481/pexels-photo-4162481.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Overhead Press', icon:'🙌', sets:4, reps:'5-6', rest:'2 min',
      tip:'Zwaar maar gecontroleerd. Core staat aan alsof je een dreun verwacht.',
      tip_en:'Heavy but controlled. Core braced as if expecting a hit.',
      youtube:'https://www.youtube.com/watch?v=2yjwXTZQDDI',
      photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Push Press', icon:'🙌', sets:4, reps:'5-6', rest:'2 min', tip:'Gebruik lichte kniebuiging voor impuls. Zwaarder gewicht mogelijk dan strict press.', tip_en:'Use a slight knee bend for momentum. Heavier weight possible than a strict press.', youtube:'https://www.youtube.com/watch?v=iaBVSJm78ko', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Arnold Press', icon:'🔄', sets:4, reps:'8', rest:'90 sec', tip:'Start met palmen naar je toe, roteer tijdens de press. Volledige schouderbewegig.', tip_en:'Start with palms facing you, rotate during the press. Full shoulder movement.', youtube:'https://www.youtube.com/watch?v=6Z15_WdXmVw', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Farmer Carry', icon:'🧳', sets:3, reps:'40 meter', rest:'90 sec',
      tip:'Zwaar gewicht in beide handen, recht lopen. Schouders naar achteren en omlaag.',
      tip_en:'Heavy weight in both hands, walk straight. Shoulders back and down.',
      youtube:'https://www.youtube.com/watch?v=rt17lmnaLSM',
      photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Suitcase Carry', icon:'💼', sets:3, reps:'30 meter per kant', rest:'90 sec', tip:'Eén kant beladen. Romp stabiel houden, niet naar de kant hangen.', tip_en:'One side loaded. Keep your torso stable, do not lean to the side.', youtube:'https://www.youtube.com/watch?v=rt17lmnaLSM', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Trap Bar Carry', icon:'🔷', sets:3, reps:'40 meter', rest:'90 sec', tip:'Ergonomischer dan dumbbells. Gewicht naast je lichaam.', tip_en:'More ergonomic than dumbbells. Weight next to your body.', youtube:'https://www.youtube.com/watch?v=rt17lmnaLSM', photo:'https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
    { name:'Face Pull', icon:'🎯', sets:3, reps:'15', rest:'60 sec',
      tip:'Afsluitende oefening voor de schouders. Trek naar je gezicht, ellebogen hoog.',
      tip_en:'Finishing exercise for the shoulders. Pull towards your face, elbows high.',
      youtube:'https://www.youtube.com/watch?v=rep-qVOkqgk',
      photo:'https://images.pexels.com/photos/4162481/pexels-photo-4162481.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
      alts:[
        { name:'Band Pull Apart', icon:'↔️', sets:3, reps:'20', rest:'45 sec', tip:'Weerstandsband voor je op borsthoogte, trek uiteen. Schouderbladen samenknijpen.', tip_en:'Resistance band in front at chest height, pull apart. Squeeze shoulder blades together.', youtube:'https://www.youtube.com/watch?v=rep-qVOkqgk', photo:'https://images.pexels.com/photos/4162481/pexels-photo-4162481.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
        { name:'Reverse Fly', icon:'🦋', sets:3, reps:'15', rest:'60 sec', tip:'Voorovergebogen, armen zijwaarts heffen. Achterkant schouders.', tip_en:'Bent forward, raise arms sideways. Rear shoulders.', youtube:'https://www.youtube.com/watch?v=Pq-mQ76-VWg', photo:'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop'},
      ]},
  ]
};


// ========== MAALTIJDPLAN ==========
// Vaste dagdoelen per energieniveau (kcal/eiwit/koolh/vet) - deze worden
// overal in de app gebruikt voor voedingsdoelen, ONGEACHT welke gerechten
// er in de ontbijt/lunch/avond/snack-lijsten staan. De testmaaltijden die
// hier eerder stonden zijn verwijderd; de coach voegt nu eigen gerechten
// toe via de "+ Gerecht toevoegen"-tab (zie customMeals in state.js).
const MEALS = {
  herstel: {
    doel: { kcal:1800, prot:130, carb:170, fat:60 },
    ontbijt: [], lunch: [], avond: [], snack: []
  },
  normaal: {
    doel: { kcal:2200, prot:160, carb:240, fat:70 },
    ontbijt: [], lunch: [], avond: [], snack: []
  },
  zwaar: {
    doel: { kcal:2800, prot:200, carb:320, fat:80 },
    ontbijt: [], lunch: [], avond: [], snack: []
  }
};


// ========== CLAUDE SYSTEEM PROMPT ==========
const SYSTEM = `Je bent coach Ira, een AI lifestyle coach. Direct, nuchter, warm en motiverend. Geen zweverige termen. Je combineert coachende vragen met concreet advies voor duurzame leefstijlverandering. Jij en je vrouw zijn zelf in 2018 volledig overgestapt naar een gezonde leefstijl — van overgewicht en gezondheidsklachten naar een sterk, fit lichaam. Dat maakt je geloofwaardig en menselijk. Antwoord altijd in het Nederlands. Maximaal 120 woorden per antwoord. Geen opsommingslijsten tenzij gevraagd.`;

const SYSTEM_EN = `You are coach Ira, an AI lifestyle coach. Direct, down-to-earth, warm and motivating. No fluffy terms. You combine coaching questions with concrete advice for sustainable lifestyle change. You and your wife made a full switch to a healthy lifestyle yourselves in 2018 — from being overweight and dealing with health issues to a strong, fit body. That makes you credible and human. Always answer in English. Maximum 120 words per answer. No bullet lists unless asked for.`;

// ========== BASISPRODUCTEN ==========
// Macros per 100g: kcal, prot, carb, fat
const PRODUCTS = [
  // FRUIT
  { id:'p1', name:'Appel', name_en:'Apple', icon:'🍎', cat:'fruit', kcal:48, prot:0, carb:12, fat:0, photo:'images/producten/p1.jpg'},
  { id:'p2', name:'Banaan', name_en:'Banana', icon:'🍌', cat:'fruit', kcal:87, prot:1.1, carb:20, fat:0.3, photo:'images/producten/p2.jpg'},
  { id:'p3', name:'Aardbei', name_en:'Strawberry', icon:'🍓', cat:'fruit', kcal:32, prot:0.7, carb:8, fat:0.3, photo:'images/producten/p3.jpg'},
  { id:'p4', name:'Bosbes', name_en:'Blueberry', icon:'🫐', cat:'fruit', kcal:57, prot:0.7, carb:14, fat:0.3, photo:'images/producten/p4.jpg'},
  { id:'p5', name:'Sinaasappel', name_en:'Orange', icon:'🍊', cat:'fruit', kcal:47, prot:0.9, carb:12, fat:0.1, photo:'images/producten/p5.jpg'},
  { id:'p6', name:'Mango', name_en:'Mango', icon:'🥭', cat:'fruit', kcal:60, prot:0.8, carb:15, fat:0.4, photo:'images/producten/p6.jpg'},
  { id:'p7', name:'Peer', name_en:'Pear', icon:'🍐', cat:'fruit', kcal:57, prot:0.4, carb:15, fat:0.1, photo:'images/producten/p7.jpg'},
  { id:'p8', name:'Watermeloen', name_en:'Watermelon', icon:'🍉', cat:'fruit', kcal:30, prot:0.6, carb:8, fat:0.2, photo:'images/producten/p8.jpg'},
  { id:'p9', name:'Druiven', name_en:'Grapes', icon:'🍇', cat:'fruit', kcal:67, prot:0.6, carb:17, fat:0.4, photo:'images/producten/p9.jpg'},
  { id:'p10', name:'Kiwi', name_en:'Kiwi', icon:'🥝', cat:'fruit', kcal:61, prot:1.1, carb:15, fat:0.5, photo:'images/producten/p10.jpg'},
  // GROENTE
  { id:'g1', name:'Broccoli', name_en:'Broccoli', icon:'🥦', cat:'groente', kcal:20, prot:2.7, carb:0.7, fat:0.7, photo:'images/producten/g1.jpg'},
  { id:'g2', name:'Spinazie', name_en:'Spinach', icon:'🥬', cat:'groente', kcal:23, prot:2.9, carb:4, fat:0.4, photo:'images/producten/g2.jpg'},
  { id:'g3', name:'Wortel', name_en:'Carrot', icon:'🥕', cat:'groente', kcal:27, prot:1, carb:5.2, fat:0.2, photo:'images/producten/g3.jpg'},
  { id:'g4', name:'Komkommer', name_en:'Cucumber', icon:'🥒', cat:'groente', kcal:12, prot:0.7, carb:1.3, fat:0.4, photo:'images/producten/g4.jpg'},
  { id:'g5', name:'Tomaat', name_en:'Tomato', icon:'🍅', cat:'groente', kcal:27, prot:0.9, carb:4, fat:0.8, photo:'images/producten/g5.jpg'},
  { id:'g6', name:'Paprika', name_en:'Bell pepper', icon:'🫑', cat:'groente', kcal:21, prot:0.8, carb:4.1, fat:0.2, photo:'images/producten/g6.jpg'},
  { id:'g7', name:'Zoete aardappel', name_en:'Sweet potato', icon:'🍠', cat:'groente', kcal:92, prot:1.2, carb:21, fat:0.3, photo:'images/producten/g7.jpg'},
  { id:'g8', name:'Courgette', name_en:'Zucchini', icon:'🥬', cat:'groente', kcal:16, prot:1.3, carb:2.3, fat:0.2, photo:'images/producten/g8.jpg'},
  { id:'g9', name:'Bloemkool', name_en:'Cauliflower', icon:'🥦', cat:'groente', kcal:21, prot:1.9, carb:3, fat:0.2, photo:'images/producten/g9.jpg'},
  { id:'g10', name:'Sperziebonen', name_en:'Green beans', icon:'🫛', cat:'groente', kcal:30, prot:2, carb:5, fat:0.2, photo:'images/producten/g10.jpg'},
  { id:'g11', name:'Avocado', name_en:'Avocado', icon:'🥑', cat:'groente', kcal:326, prot:3.8, carb:3.2, fat:33.1, photo:'images/producten/g11.jpg'},
  { id:'g12', name:'Ui', name_en:'Onion', icon:'🧅', cat:'groente', kcal:32, prot:1.3, carb:6.3, fat:0.2, photo:'images/producten/g12.jpg'},
  { id:'g13', name:'Doperwten', name_en:'Green peas', icon:'🫛', cat:'groente', kcal:81, prot:5.4, carb:14, fat:0.4, photo:'images/producten/g13.jpg'},
  { id:'g14', name:'Champignons', name_en:'Mushrooms', icon:'🍄', cat:'groente', kcal:28, prot:2.5, carb:4.3, fat:0.1, photo:'images/producten/g14.jpg'},
  { id:'g15', name:'Aziatische Wokgroenten', name_en:'Asian wok vegetables', icon:'🥬', cat:'groente', kcal:19, prot:3.5, carb:0.1, fat:0.5, photo:'images/producten/g15.jpg'},
  { id:'g16', name:'Azië Wokmix (diepvries)', name_en:'Asia wok mix (frozen)', icon:'🥬', cat:'groente', kcal:24, prot:2, carb:3.4, fat:0.3, photo:'images/producten/g16.jpg'},
  { id:'g17', name:'Pompoen', name_en:'Pumpkin', icon:'🎃', cat:'groente', kcal:35, prot:1, carb:7, fat:0.3, photo:'images/producten/g17.jpg'},
  { id:'g18', name:'Wortelpeterselie', name_en:'Hamburg parsley root', icon:'🥕', cat:'groente', kcal:46, prot:2.3, carb:8, fat:0.5, photo:'images/producten/g18.jpg'},
  { id:'g19', name:'Spruiten', name_en:'Brussels sprouts', icon:'🥦', cat:'groente', kcal:34, prot:4.5, carb:3.3, fat:0.3, photo:'images/producten/g19.jpg'},
  { id:'g20', name:'Asperges', name_en:'Asparagus', icon:'🌱', cat:'groente', kcal:16, prot:1, carb:3, fat:0, photo:'images/producten/g20.jpg'},
  { id:'g21', name:'Tuinerwten', name_en:'Garden peas', icon:'🫛', cat:'groente', kcal:79, prot:6.6, carb:12, fat:0.5, photo:'images/producten/g21.jpg'},
  { id:'g22', name:'Koolraap', name_en:'Kohlrabi', icon:'🥬', cat:'groente', kcal:26, prot:1, carb:5, fat:0.2, photo:'images/producten/g22.jpg'},
  // VLEES
  { id:'v1', name:'Kipfilet', name_en:'Chicken breast', icon:'🍗', cat:'vlees', kcal:113, prot:23, carb:0, fat:2.3, photo:'images/producten/v1.jpg'},
  { id:'v2', name:'Kipgehakt', name_en:'Ground chicken', icon:'🍗', cat:'vlees', kcal:143, prot:17, carb:0, fat:8, photo:'images/producten/v2.jpg'},
  { id:'v3', name:'Rundergehakt (mager)', name_en:'Ground beef (lean)', icon:'🥩', cat:'vlees', kcal:154, prot:21, carb:0, fat:7, photo:'images/producten/v3.jpg'},
  { id:'v4', name:'Biefstuk', name_en:'Steak', icon:'🥩', cat:'vlees', kcal:180, prot:26, carb:0, fat:8, photo:'images/producten/v4.jpg'},
  { id:'v5', name:'Kalkoenfilet', name_en:'Turkey breast', icon:'🍗', cat:'vlees', kcal:104, prot:22, carb:0, fat:1.5, photo:'images/producten/v5.jpg'},
  { id:'v6', name:'Pulled chicken', name_en:'Pulled chicken', icon:'🍗', cat:'vlees', kcal:130, prot:24, carb:0, fat:3, photo:'images/producten/v6.jpg'},
  { id:'v7', name:'Spek (mager)', name_en:'Bacon (lean)', icon:'🥓', cat:'vlees', kcal:218, prot:14, carb:0, fat:18, photo:'images/producten/v7.jpg'},
  { id:'v8', name:'Hamburger (mager)', name_en:'Hamburger (lean)', icon:'🍔', cat:'vlees', kcal:165, prot:20, carb:0, fat:9, photo:'images/producten/v8.jpg'},
  { id:'v9', name:'Rosbief', name_en:'Roast beef', icon:'🥩', cat:'vlees', kcal:149, prot:22, carb:0, fat:6.5, photo:'images/producten/v9.jpg'},
  { id:'v10', name:'Lamsvlees', name_en:'Lamb', icon:'🍖', cat:'vlees', kcal:294, prot:25, carb:0, fat:21, photo:'images/producten/v10.jpg'},
  { id:'v11', name:'Hertenbiefstuk', name_en:'Venison steak', icon:'🦌', cat:'vlees', kcal:120, prot:22, carb:0, fat:3.6, photo:'images/producten/v11.jpg'},
  { id:'v12', name:'Hertenhamburger', name_en:'Venison burger', icon:'🦌', cat:'vlees', kcal:120, prot:22, carb:0, fat:3.6, photo:'images/producten/v12.jpg'},
  { id:'v13', name:'Hertenstoof', name_en:'Venison stew meat', icon:'🦌', cat:'vlees', kcal:120, prot:22, carb:0, fat:3.6, photo:'images/producten/v13.jpg'},
  { id:'v14', name:'Hertenworstjes', name_en:'Venison sausages', icon:'🦌', cat:'vlees', kcal:200, prot:16.1, carb:0.2, fat:15, photo:'images/producten/v14.jpg'},
  { id:'v15', name:'Runderstoof', name_en:'Beef stew meat', icon:'🥩', cat:'vlees', kcal:106, prot:22, carb:0, fat:2, photo:'images/producten/v15.jpg'},
  { id:'v16', name:'Runderhamburger', name_en:'Beef burger', icon:'🍔', cat:'vlees', kcal:232, prot:18, carb:4, fat:16, photo:'images/producten/v16.jpg'},
  { id:'v17', name:'Herten/runderhamburger', name_en:'Venison/beef burger', icon:'🍔', cat:'vlees', kcal:176, prot:20, carb:2, fat:9.8, photo:'images/producten/v17.jpg'},
  { id:'v18', name:'Kipshoarma', name_en:'Chicken shoarma', icon:'🍗', cat:'vlees', kcal:92, prot:19, carb:0, fat:1.8, photo:'images/producten/v18.jpg'},
  // VIS
  { id:'f1', name:'Kweekzalm', name_en:'Farmed salmon', icon:'🐟', cat:'vis', kcal:225, prot:18, carb:0, fat:17, photo:'images/producten/f1.jpg'},
  { id:'f13', name:'Wilde zalm', name_en:'Wild salmon', icon:'🐟', cat:'vis', kcal:123, prot:24, carb:0, fat:3, photo:'images/producten/f13.jpg'},
  { id:'f2', name:'Tonijn (blik, water)', name_en:'Tuna (canned, water)', icon:'🐟', cat:'vis', kcal:84, prot:19, carb:0, fat:0.5, photo:'images/producten/f2.jpg'},
  { id:'f3', name:'Kabeljauw', name_en:'Cod', icon:'🐠', cat:'vis', kcal:82, prot:18, carb:0, fat:0.7, photo:'images/producten/f3.jpg'},
  { id:'f4', name:'Tilapia', name_en:'Tilapia', icon:'🐠', cat:'vis', kcal:96, prot:20, carb:0, fat:1.7, photo:'images/producten/f4.jpg'},
  { id:'f5', name:'Makreel', name_en:'Mackerel', icon:'🐟', cat:'vis', kcal:205, prot:19, carb:0, fat:14, photo:'images/producten/f5.jpg'},
  { id:'f6', name:'Garnalen', name_en:'Shrimp', icon:'🦐', cat:'vis', kcal:85, prot:18, carb:1, fat:1, photo:'images/producten/f6.jpg'},
  { id:'f7', name:'Haring', name_en:'Herring', icon:'🐟', cat:'vis', kcal:158, prot:18, carb:0, fat:9, photo:'images/producten/f7.jpg'},
  { id:'f8', name:"Gamba's", name_en:'King prawns', icon:'🦐', cat:'vis', kcal:99, prot:24, carb:0.2, fat:0.3, photo:'images/producten/f8.jpg'},
  { id:'f9', name:'Witvis', name_en:'White fish', icon:'🐟', cat:'vis', kcal:90, prot:20, carb:0, fat:1, photo:'images/producten/f9.jpg'},
  { id:'f10', name:'Kreeft', name_en:'Lobster', icon:'🦞', cat:'vis', kcal:89, prot:19, carb:0, fat:0.9, photo:'images/producten/f10.jpg'},
  { id:'f11', name:'Paling', name_en:'Eel', icon:'🐟', cat:'vis', kcal:236, prot:18, carb:0, fat:18, photo:'images/producten/f11.jpg'},
  { id:'f12', name:'Sardines', name_en:'Sardines', icon:'🐟', cat:'vis', kcal:208, prot:25, carb:0, fat:11, photo:'images/producten/f12.jpg'},
  // ZUIVEL
  { id:'z1', name:'Griekse yoghurt (0%)', name_en:'Greek yogurt (0%)', icon:'🥛', cat:'zuivel', kcal:59, prot:10, carb:4, fat:0.4, photo:'images/producten/z1.jpg'},
  { id:'z2', name:'Kwark', name_en:'Quark', icon:'🥛', cat:'zuivel', kcal:57, prot:9, carb:4, fat:0.2, photo:'images/producten/z2.jpg'},
  { id:'z3', name:'Cottage cheese', name_en:'Cottage cheese', icon:'🧀', cat:'zuivel', kcal:98, prot:11, carb:3, fat:4, photo:'images/producten/z3.jpg'},
  { id:'z4', name:'Eieren', name_en:'Eggs', icon:'🥚', cat:'zuivel', kcal:142, prot:12, carb:1, fat:10, portie:{ gram:50, label:'1 ei', label_en:'1 egg' }, photo:'images/producten/z4.jpg'},
  { id:'z5', name:'Volle melk', name_en:'Whole milk', icon:'🥛', cat:'zuivel', kcal:61, prot:3.2, carb:5, fat:3.5, photo:'images/producten/z5.jpg'},
  { id:'z6', name:'Halfvolle melk', name_en:'Semi-skimmed milk', icon:'🥛', cat:'zuivel', kcal:46, prot:3.4, carb:5, fat:1.5, photo:'images/producten/z6.jpg'},
  { id:'z7', name:'Mozzarella', name_en:'Mozzarella', icon:'🧀', cat:'zuivel', kcal:280, prot:18, carb:3, fat:22, photo:'images/producten/z7.jpg'},
  { id:'z8', name:'Eiwitpoeder (whey)', name_en:'Protein powder (whey)', icon:'🥛', cat:'zuivel', kcal:380, prot:80, carb:8, fat:5, photo:'images/producten/z8.jpg'},
  { id:'z9', name:'Eiwit', name_en:'Egg white', icon:'🥚', cat:'zuivel', kcal:52, prot:11, carb:0.7, fat:0.2, photo:'images/producten/z9.jpg'},
  { id:'z10', name:'Skyr', name_en:'Skyr', icon:'🥛', cat:'zuivel', kcal:63, prot:11, carb:4, fat:0.2, photo:'images/producten/z10.jpg'},
  { id:'z11', name:'Kaas 20+', name_en:'Cheese (20+ fat)', icon:'🧀', cat:'zuivel', kcal:264, prot:24, carb:0, fat:19, photo:'images/producten/z11.jpg'},
  { id:'z12', name:'Eigeel', name_en:'Egg yolk', icon:'🥚', cat:'zuivel', kcal:322, prot:16, carb:3.6, fat:27, photo:'images/producten/z12.jpg'},
  { id:'z13', name:'Kaas 45+', name_en:'Cheese (45+ fat)', icon:'🧀', cat:'zuivel', kcal:350, prot:25, carb:0, fat:28, photo:'images/producten/z13.jpg'},
  { id:'z14', name:'Eiwitpoeder (Evou)', name_en:'Protein powder (Evou)', icon:'🥛', cat:'zuivel', kcal:373, prot:77, carb:8.7, fat:3.3, photo:'images/producten/z14.jpg'},
  { id:'z15', name:'Eiwitpoeder (Nutribites)', name_en:'Protein powder (Nutribites)', icon:'🥛', cat:'zuivel', kcal:365, prot:68.7, carb:7.7, fat:6.6, photo:'images/producten/z15.jpg'},
  { id:'z16', name:'Boeren skyr (Weeribben)', name_en:'Farm skyr (Weeribben)', icon:'🥛', cat:'zuivel', kcal:79, prot:10, carb:6.4, fat:1.5, photo:'images/producten/z16.jpg'},
  // GRANEN
  { id:'gr1', name:'Havermout', name_en:'Oatmeal', icon:'🥣', cat:'granen', kcal:368, prot:13, carb:66, fat:7, photo:'images/producten/gr1.jpg'},
  { id:'gr2', name:'Volkoren brood', name_en:'Wholegrain bread', icon:'🍞', cat:'granen', kcal:247, prot:9, carb:41, fat:3, photo:'images/producten/gr2.jpg'},
  { id:'gr3', name:'Witte rijst (gekookt)', name_en:'White rice (cooked)', icon:'🍚', cat:'granen', kcal:130, prot:2.7, carb:28, fat:0.3, photo:'images/producten/gr3.jpg'},
  { id:'gr4', name:'Zilvervliesrijst (gekookt)', name_en:'Brown rice (cooked)', icon:'🍚', cat:'granen', kcal:112, prot:2.6, carb:24, fat:0.9, photo:'images/producten/gr4.jpg'},
  { id:'gr5', name:'Quinoa (gekookt)', name_en:'Quinoa (cooked)', icon:'🌾', cat:'granen', kcal:120, prot:4.4, carb:22, fat:1.9, photo:'images/producten/gr5.jpg'},
  { id:'gr6', name:'Pasta (gekookt)', name_en:'Pasta (cooked)', icon:'🍝', cat:'granen', kcal:158, prot:5.8, carb:31, fat:0.9, photo:'images/producten/gr6.jpg'},
  { id:'gr7', name:'Aardappel (gekookt)', name_en:'Potato (cooked)', icon:'🥔', cat:'granen', kcal:77, prot:2.0, carb:17, fat:0.1, photo:'images/producten/gr7.jpg'},
  { id:'gr8', name:'Granola', name_en:'Granola', icon:'🥣', cat:'granen', kcal:471, prot:10, carb:64, fat:20, photo:'images/producten/gr8.jpg'},
  { id:'gr9', name:'Rijstwafels', name_en:'Rice cakes', icon:'🫓', cat:'granen', kcal:387, prot:8, carb:82, fat:3, photo:'images/producten/gr9.jpg'},
  { id:'gr10', name:'Couscous (gekookt)', name_en:'Couscous (cooked)', icon:'🌾', cat:'granen', kcal:112, prot:3.8, carb:23, fat:0.2, photo:'images/producten/gr10.jpg'},
  { id:'gr11', name:'Volkoren basmatirijst (gekookt)', name_en:'Wholegrain basmati rice (cooked)', icon:'🍚', cat:'granen', kcal:123, prot:3.5, carb:25, fat:1, photo:'images/producten/gr11.jpg'},
  { id:'gr12', name:'Volkoren pasta (gekookt)', name_en:'Wholegrain pasta (cooked)', icon:'🍝', cat:'granen', kcal:124, prot:5, carb:25, fat:1.1, photo:'images/producten/gr12.jpg'},
  { id:'gr13', name:'Volkoren couscous (gekookt)', name_en:'Wholegrain couscous (cooked)', icon:'🌾', cat:'granen', kcal:112, prot:4.5, carb:23, fat:0.6, photo:'images/producten/gr13.jpg'},
  { id:'gr14', name:'Volkoren wraps', name_en:'Wholegrain wraps', icon:'🌯', cat:'granen', kcal:245, prot:8, carb:40, fat:6, photo:'images/producten/gr14.jpg'},
  { id:'gr15', name:'Brinta', name_en:'Brinta (wheat bran cereal)', icon:'🥣', cat:'granen', kcal:350, prot:11, carb:65, fat:3.5, photo:'images/producten/gr15.jpg'},
  { id:'gr16', name:'Boekweit (gekookt)', name_en:'Buckwheat (cooked)', icon:'🌾', cat:'granen', kcal:92, prot:3.4, carb:20, fat:0.6, photo:'images/producten/gr16.jpg'},
  { id:'gr17', name:'Desem volkoren (brood)', name_en:'Sourdough wholegrain bread', icon:'🍞', cat:'granen', kcal:221, prot:11.1, carb:39, fat:2.3, photo:'images/producten/gr17.jpg'},
  { id:'gr18', name:'Frites', name_en:'French fries', icon:'🍟', cat:'granen', kcal:84, prot:2, carb:19, fat:0, photo:'images/producten/gr18.jpg'},
  // NOTEN & ZADEN
  { id:'n1', name:'Amandelen', name_en:'Almonds', icon:'🌰', cat:'noten', kcal:582, prot:22.3, carb:3.9, fat:53, photo:'images/producten/n1.jpg'},
  { id:'n2', name:'Walnoten', name_en:'Walnuts', icon:'🌰', cat:'noten', kcal:676, prot:15.2, carb:7, fat:65.2, photo:'images/producten/n2.jpg'},
  { id:'n3', name:'Cashewnoten', name_en:'Cashews', icon:'🌰', cat:'noten', kcal:553, prot:18, carb:30, fat:44, photo:'images/producten/n3.jpg'},
  { id:'n4', name:'Pindakaas', name_en:'Peanut butter', icon:'🫙', cat:'noten', kcal:588, prot:25, carb:20, fat:50, photo:'images/producten/n4.jpg'},
  { id:'n5', name:'Chiazaad', name_en:'Chia seeds', icon:'🌱', cat:'noten', kcal:486, prot:17, carb:42, fat:31, photo:'images/producten/n5.jpg'},
  { id:'n6', name:'Lijnzaad', name_en:'Flaxseed', icon:'🌱', cat:'noten', kcal:534, prot:18, carb:29, fat:42, photo:'images/producten/n6.jpg'},
  { id:'n7', name:'Pompoenpitten', name_en:'Pumpkin seeds', icon:'🌱', cat:'noten', kcal:446, prot:19, carb:54, fat:19, photo:'images/producten/n7.jpg'},
  { id:'n8', name:'Hazelnoten', name_en:'Hazelnuts', icon:'🌰', cat:'noten', kcal:628, prot:15, carb:17, fat:61, photo:'images/producten/n8.jpg'},
  { id:'n9', name:'Pecannoten', name_en:'Pecans', icon:'🌰', cat:'noten', kcal:691, prot:9, carb:14, fat:72, photo:'images/producten/n9.jpg'},
  { id:'n10', name:'Pijnboompitten', name_en:'Pine nuts', icon:'🌰', cat:'noten', kcal:673, prot:14, carb:13, fat:68, photo:'images/producten/n10.jpg'},
  { id:'n11', name:'Sesamzaad', name_en:'Sesame seeds', icon:'🌱', cat:'noten', kcal:573, prot:18, carb:23, fat:50, photo:'images/producten/n11.jpg'},
  { id:'n12', name:'Zonnebloempitten', name_en:'Sunflower seeds', icon:'🌻', cat:'noten', kcal:584, prot:21, carb:20, fat:51, photo:'images/producten/n12.jpg'},
  // OVERIG
  { id:'o1', name:'Hummus', name_en:'Hummus', icon:'🫙', cat:'overig', kcal:166, prot:8, carb:14, fat:10, photo:'images/producten/o1.jpg'},
  { id:'o2', name:'Olijfolie', name_en:'Olive oil', icon:'🫒', cat:'overig', kcal:884, prot:0, carb:0, fat:100, photo:'images/producten/o2.jpg'},
  { id:'o3', name:'Honing', name_en:'Honey', icon:'🍯', cat:'overig', kcal:304, prot:0.3, carb:82, fat:0, photo:'images/producten/o3.jpg'},
  { id:'o4', name:'Edamame', name_en:'Edamame', icon:'🫘', cat:'overig', kcal:121, prot:11, carb:9, fat:5, photo:'images/producten/o4.jpg'},
  { id:'o5', name:'Linzen', name_en:'Lentils', icon:'🫘', cat:'overig', kcal:102, prot:7.6, carb:16, fat:0.8, photo:'images/producten/o5.jpg'},
  { id:'o6', name:'Kikkererwten', name_en:'Chickpeas', icon:'🫘', cat:'overig', kcal:106, prot:6.5, carb:14, fat:2.7, photo:'images/producten/o6.jpg'},
  { id:'o7', name:'Proteinenbar', name_en:'Protein bar', icon:'🍫', cat:'overig', kcal:350, prot:25, carb:35, fat:9, photo:'images/producten/o7.jpg'},
  { id:'o8', name:'Kokosolie', name_en:'Coconut oil', icon:'🥥', cat:'overig', kcal:862, prot:0, carb:0, fat:100, photo:'images/producten/o8.jpg'},
  { id:'o9', name:'Sojabonen (gekookt)', name_en:'Soybeans (cooked)', icon:'🫘', cat:'overig', kcal:173, prot:18, carb:9, fat:9, photo:'images/producten/o9.jpg'},
  { id:'o10', name:'Seitan', name_en:'Seitan', icon:'🌱', cat:'overig', kcal:130, prot:25, carb:4, fat:2, photo:'images/producten/o10.jpg'},
  { id:'o11', name:'Tofu', name_en:'Tofu', icon:'🌱', cat:'overig', kcal:76, prot:8, carb:1.9, fat:4.8, photo:'images/producten/o11.jpg'},
  { id:'o12', name:'Tempeh', name_en:'Tempeh', icon:'🌱', cat:'overig', kcal:192, prot:20, carb:7.6, fat:11, photo:'images/producten/o12.jpg'},
  { id:'o13', name:'Zwarte bonen (gekookt)', name_en:'Black beans (cooked)', icon:'🫘', cat:'overig', kcal:132, prot:8.9, carb:24, fat:0.5, photo:'images/producten/o13.jpg'},
  { id:'o14', name:'Witte bonen (gekookt)', name_en:'White beans (cooked)', icon:'🫘', cat:'overig', kcal:139, prot:9.7, carb:25, fat:0.5, photo:'images/producten/o14.jpg'},
  { id:'o15', name:'Bruine bonen (gekookt)', name_en:'Brown beans (cooked)', icon:'🫘', cat:'overig', kcal:127, prot:8.7, carb:23, fat:0.5, photo:'images/producten/o15.jpg'},
  { id:'o16', name:'Pure chocolade', name_en:'Dark chocolate', icon:'🍫', cat:'overig', kcal:546, prot:4.9, carb:61, fat:31, photo:'images/producten/o16.jpg'},
  { id:'o17', name:'Koolzaadolie', name_en:'Rapeseed oil', icon:'🛢️', cat:'overig', kcal:884, prot:0, carb:0, fat:100, photo:'images/producten/o17.jpg'},
  { id:'o18', name:'Lijnzaadolie', name_en:'Flaxseed oil', icon:'🛢️', cat:'overig', kcal:884, prot:0, carb:0, fat:100, photo:'images/producten/o18.jpg'},
  { id:'o19', name:'Zonnebloemolie', name_en:'Sunflower oil', icon:'🛢️', cat:'overig', kcal:884, prot:0, carb:0, fat:100, photo:'images/producten/o19.jpg'},
  { id:'o20', name:'Cacaopoeder', name_en:'Cocoa powder', icon:'🍫', cat:'overig', kcal:255, prot:25.2, carb:13.7, fat:11, photo:'images/producten/o20.jpg'},
  { id:'o21', name:'Cacao nibs', name_en:'Cacao nibs', icon:'🍫', cat:'overig', kcal:488, prot:13.4, carb:2.5, fat:47.2, photo:'images/producten/o21.jpg'},
];

// Cache-busting: elke keer dat een productfoto vervangen wordt, dit nummer ophogen.
// data.js zelf wordt al bij elke paginalaad vers opgehaald (zie _appScriptsCacheBust in
// auth.js), dus deze versie-toevoeging aan elk foto-pad zorgt dat de browser de nieuwe
// foto ook meteen ophaalt i.p.v. een oude, gecachete versie te blijven tonen.
const PRODUCT_PHOTO_VERSION = 2;
PRODUCTS.forEach(p => { if (p.photo) p.photo += '?v=' + PRODUCT_PHOTO_VERSION; });

// ========== INGEBOUWDE PROGRAMMA'S ==========
const BUILTIN_PROGRAMMAS = [
  {
    id: 'builtin-ira',
    naam: 'Basisprogramma Ira',
    naam_en: "Ira's Base Program",
    builtin: true,
    dagen: {
      0: { naam: 'Maandag', naam_en: 'Monday', oefeningen: [
        { naam: 'Squats', sets: '4', reps: '20', rust: '120s' },
        { naam: 'Plank 1 min', sets: '1', reps: '1', rust: '120s' },
        { naam: 'Optrekken Pull up', naam_en: 'Pull-up', sets: '4', reps: '10', rust: '120s' },
        { naam: 'Handtrainer', naam_en: 'Grip trainer', sets: '3', reps: '25', rust: '120s' },
        { naam: 'Wandelen', naam_en: 'Walking', sets: '', reps: '', rust: '' }
      ]},
      1: { naam: 'Dinsdag', naam_en: 'Tuesday', oefeningen: [
        { naam: 'Bench Press', sets: '2', reps: '8-12', rust: '120 sec' },
        { naam: 'Dumbbell Shoulder Press', sets: '1', reps: '10-12', rust: '120 sec' },
        { naam: 'Shoulder Bench Press', sets: '1', reps: '8-10', rust: '120 sec' },
        { naam: 'Dumbbell Fly', sets: '1', reps: '12-15', rust: '120 sec' },
        { naam: 'Concentration Curl', sets: '1', reps: '12/arm', rust: '120 sec' },
        { naam: 'Cable Upright Row', sets: '1', reps: '12-15', rust: '120 sec' },
        { naam: 'Dips 1 (bank)', sets: '1', reps: '25-30', rust: '120 sec' },
        { naam: 'Dips 2 (parallel bars)', sets: '1', reps: '15-20', rust: '120 sec' },
        { naam: 'Wandelen', naam_en: 'Walking', sets: '1', reps: '30 min', rust: '—' },
        { naam: 'Plank', sets: '1', reps: '1', rust: '120 sec' }
      ]},
      2: { naam: 'Woensdag', naam_en: 'Wednesday', oefeningen: [
        { naam: 'Ab Wheel', sets: '1', reps: '50', rust: '120 sec' },
        { naam: 'Serie abs exercises', naam_en: 'Abs circuit', sets: '1', reps: 'circuit', rust: '120 sec' },
        { naam: 'Dumbbell Squat', sets: '1', reps: '20', rust: '120 sec' },
        { naam: 'Dumbbell Lunges', sets: '1', reps: '20', rust: '120 sec' },
        { naam: 'Kettlebell Swing', sets: '1', reps: '30', rust: '120 sec' },
        { naam: 'Chin-up', sets: '4', reps: '6-10', rust: '120 sec' },
        { naam: 'Handtrainer', naam_en: 'Grip trainer', sets: '3', reps: '25/hand', rust: '120 sec' },
        { naam: 'Plank', sets: '1', reps: '60 sec', rust: '120 sec' },
        { naam: 'Wandelen', naam_en: 'Walking', sets: '1', reps: '30 min', rust: '—' }
      ]},
      3: { naam: 'Donderdag', naam_en: 'Thursday', oefeningen: [
        { naam: 'Dumbbell Press', sets: '1', reps: '10-15', rust: '120 sec' },
        { naam: 'Push-ups', sets: '1', reps: '12-15', rust: '120 sec' },
        { naam: 'Squats', sets: '3', reps: '20', rust: '120 sec' },
        { naam: 'Plank', sets: '1', reps: '60 sec', rust: '120 sec' },
        { naam: 'Back Extension', sets: '1', reps: '12-15', rust: '120 sec' },
        { naam: 'Wandelen', naam_en: 'Walking', sets: '1', reps: '30 min', rust: '—' }
      ]},
      4: { naam: 'Vrijdag', naam_en: 'Friday', oefeningen: [
        { naam: 'Squats', sets: '4', reps: '20', rust: '120 sec' },
        { naam: 'Plank', sets: '1', reps: '60 sec', rust: '120 sec' },
        { naam: 'Pull-ups', sets: '4', reps: '6-10', rust: '120 sec' },
        { naam: 'Wandelen', naam_en: 'Walking', sets: '1', reps: '30 min', rust: '—' },
        { naam: 'Ab Wheel', sets: '1', reps: '50', rust: '120 sec' },
        { naam: 'Serie abs exercises', naam_en: 'Abs circuit', sets: '1', reps: 'circuit', rust: '120 sec' }
      ]},
      5: { naam: 'Zaterdag', naam_en: 'Saturday', oefeningen: [
        { naam: 'Bench Press', sets: '2', reps: '8-12', rust: '120 sec' },
        { naam: 'Dumbbell Shoulder Press', sets: '1', reps: '10-12', rust: '120 sec' },
        { naam: 'Shoulder Bench Press', sets: '1', reps: '8-10', rust: '120 sec' },
        { naam: 'Dumbbell Fly', sets: '1', reps: '12-15', rust: '120 sec' },
        { naam: 'Concentration Curl', sets: '1', reps: '12/arm', rust: '125 sec' },
        { naam: 'Lat Pulldown', sets: '1', reps: '10-12', rust: '120 sec' },
        { naam: 'Seated Cable Row', sets: '1', reps: '10-12', rust: '120 sec' },
        { naam: 'Dips 1 (bank)', sets: '1', reps: '25-30', rust: '120 sec' },
        { naam: 'Plank', sets: '1', reps: '60 sec', rust: '120 sec' },
        { naam: 'Wandelen', naam_en: 'Walking', sets: '1', reps: '30 min', rust: '—' }
      ]},
      6: { naam: 'Zondag', naam_en: 'Sunday', oefeningen: [
        { naam: 'Ab Wheel', sets: '1', reps: '50', rust: '120sec' },
        { naam: 'Serie abs exercises', naam_en: 'Abs circuit', sets: '1', reps: 'circuit', rust: '120sec' },
        { naam: 'Dumbbell Squat', sets: '1', reps: '20', rust: '120 sec' },
        { naam: 'Back Extension', sets: '1', reps: '20', rust: '120 sec' },
        { naam: 'Plank', sets: '1', reps: '60 sec', rust: '120 sec' },
        { naam: 'Wandelen', naam_en: 'Walking', sets: '1', reps: '30 min', rust: '—' }
      ]}
    }
  }
];
